<?php
// src/Validation/Cache/RuleCacheGenerator.php

declare(strict_types=1);

namespace Roster\Validation\Cache;

use Carbon\Carbon;
use Roster\Enums\EntityType;
use Roster\Enums\OperationType;
use Roster\Validation\RuleScanner;
use Roster\Validation\Attributes\ValidationRule;

class RuleCacheGenerator
{
    private string $cachePath;

    public function __construct(
        private RuleScanner $ruleScanner,
        ?string $cachePath = null
    ) {
        $this->cachePath = $cachePath ?? storage_path('framework/cache/roster_rules.php');
    }

    public function generate(): bool
    {
        $rules = $this->ruleScanner->scan();
        $content = $this->buildCacheFile($rules);

        // Créer le répertoire si nécessaire
        $directory = dirname($this->cachePath);
        if (!is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        // Écrire le fichier atomiquement
        $tempFile = $this->cachePath . '.tmp';
        if (file_put_contents($tempFile, $content) === false) {
            return false;
        }

        return rename($tempFile, $this->cachePath);
    }

    public function getCachePath(): string
    {
        return $this->cachePath;
    }

    public function isCacheFresh(): bool
    {
        if (!file_exists($this->cachePath)) {
            return false;
        }

        // Vérifier si le fichier a été généré il y a moins de X heures
        $maxAge = config('roster-validation.cache_max_age_hours', 24);
        return (Carbon::now()
            ->getTimestamp() - filemtime($this->cachePath)) < ($maxAge * 3600);
    }

    public function clear(): bool
    {
        if (file_exists($this->cachePath)) {
            return unlink($this->cachePath);
        }

        return true;
    }

    private function buildCacheFile(array $rules): string
    {
        $timestamp = Carbon::now()
            ->format('Y-m-d H:i:s');
        $rulesCount = count($rules);

        $content = <<<PHP
<?php
// ==============================================
// GENERATED ROSTER VALIDATION RULES CACHE
// Generated: {$timestamp}
// Rules count: {$rulesCount}
// DO NOT EDIT THIS FILE MANUALLY
// ==============================================

declare(strict_types=1);

return [

PHP;

        foreach ($rules as $className => $attribute) {
            $content .= $this->buildRuleEntry($className, $attribute);
        }

        return $content . "];\n";
    }

    private function buildRuleEntry(string $className, ValidationRule $validationRule): string
    {
        $entities = array_map(fn(EntityType $entityType) => $entityType->value, $validationRule->entities);
        $operations = array_map(fn(OperationType $operationType) => $operationType->value, $validationRule->operations);

        $indent = '    ';
        $entry = $indent . "'" . addslashes($className) . "' => [\n";
        $entry .= $indent . $indent . "'priority' => " . $validationRule->priority . ",\n";
        $entry .= $indent . $indent . "'entities' => [" . implode(', ', array_map(fn(string $e): string => sprintf("'%s'", $e), $entities)) . "],\n";
        $entry .= $indent . $indent . "'operations' => [" . implode(', ', array_map(fn(string $o): string => sprintf("'%s'", $o), $operations)) . "],\n";
        $entry .= $indent . $indent . "'class' => '" . addslashes($className) . "',\n";

        return $entry . ($indent . "],\n");
    }
}
