<?php

declare(strict_types=1);

namespace Roster\Validation\Cache;

use Illuminate\Support\Carbon;
use Roster\Enums\EntityType;
use Roster\Enums\OperationType;
use Roster\Validation\RuleScanner;
use Roster\Validation\Attributes\ValidationRule;

/**
 * Generates and manages cached validation rules for the roster system.
 *
 * Responsible for scanning validation rule classes, compiling them into an optimized cache file,
 * and providing cache freshness checks to ensure validation rules are up-to-date.
 */
class RuleCacheGenerator
{
    private string $cachePath;

    public function __construct(
        private RuleScanner $ruleScanner,
        ?string $cachePath = null
    ) {
        $this->cachePath = $cachePath ?? storage_path('framework/cache/roster_rules.php');
    }

    /**
     * Generates the validation rules cache file.
     *
     * Scans for validation rules and writes them to an optimized cache file.
     *
     * @return bool True if cache generation succeeded
     */
    public function generate(): bool
    {
        $rules = $this->ruleScanner->scan();
        $content = $this->buildCacheFile($rules);

        $directory = dirname($this->cachePath);
        if (!is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $temporaryFilePath = $this->cachePath . '.tmp';
        if (file_put_contents($temporaryFilePath, $content) === false) {
            return false;
        }

        return rename($temporaryFilePath, $this->cachePath);
    }

    /**
     * Gets the current cache file path.
     *
     * @return string Absolute path to the cache file
     */
    public function getCachePath(): string
    {
        return $this->cachePath;
    }

    /**
     * Checks if the cache is fresh and should be used.
     *
     * @return bool True if cache exists and is within freshness threshold
     */
    public function isCacheFresh(): bool
    {
        if (!file_exists($this->cachePath)) {
            return false;
        }

        $maximumAgeInHours = config('roster.cache.cache_max_age_hours', 24);
        $cacheAgeInSeconds = Carbon::now()->getTimestamp() - filemtime($this->cachePath);
        $maximumAgeInSeconds = $maximumAgeInHours * 3600;

        return $cacheAgeInSeconds < $maximumAgeInSeconds;
    }

    /**
     * Clears the validation rules cache.
     *
     * @return bool True if cache was successfully cleared or didn't exist
     */
    public function clear(): bool
    {
        if (file_exists($this->cachePath)) {
            return unlink($this->cachePath);
        }

        return true;
    }

    /**
     * Builds the cache file content from scanned rules.
     *
     * @param array<string, ValidationRule> $rules Scanned validation rules
     * @return string Complete cache file content
     */
    private function buildCacheFile(array $rules): string
    {
        $generationTimestamp = Carbon::now()->format('Y-m-d H:i:s');
        $rulesCount = count($rules);

        $cacheHeader = $this->buildCacheHeader($generationTimestamp, $rulesCount);
        $cacheBody = $this->buildCacheBody($rules);

        return $cacheHeader . $cacheBody . "];\n";
    }

    /**
     * Builds the cache header with metadata.
     *
     * @param string $generationTimestamp When the cache was generated
     * @param int $rulesCount Number of rules in cache
     * @return string Cache header content
     */
    private function buildCacheHeader(string $generationTimestamp, int $rulesCount): string
    {
        return <<<PHP
<?php
// ==============================================
// GENERATED ROSTER VALIDATION RULES CACHE
// Generated: {$generationTimestamp}
// Rules count: {$rulesCount}
// DO NOT EDIT THIS FILE MANUALLY
// ==============================================

declare(strict_types=1);

return [

PHP;
    }

    /**
     * Builds the cache body with all rule entries.
     *
     * @param array<string, ValidationRule> $rules Validation rules to cache
     * @return string Cache body content
     */
    private function buildCacheBody(array $rules): string
    {
        $body = '';
        foreach ($rules as $className => $validationRule) {
            $body .= $this->buildRuleEntry($className, $validationRule);
        }
        return $body;
    }

    /**
     * Builds a single rule entry for the cache file.
     *
     * @param string $className Validation rule class name
     * @param ValidationRule $validationRule Validation rule attribute
     * @return string Formatted rule entry
     */
    private function buildRuleEntry(string $className, ValidationRule $validationRule): string
    {
        $entities = $this->extractEnumValues($validationRule->entities, EntityType::class);
        $operations = $this->extractEnumValues($validationRule->operations, OperationType::class);

        $indent = '    ';
        $entry = $indent . "'" . addslashes($className) . "' => [\n";
        $entry .= $indent . $indent . "'priority' => " . $validationRule->priority . ",\n";
        $entry .= $indent . $indent . "'entities' => [" . $this->formatArrayValues($entities) . "],\n";
        $entry .= $indent . $indent . "'operations' => [" . $this->formatArrayValues($operations) . "],\n";
        $entry .= $indent . $indent . "'class' => '" . addslashes($className) . "',\n";

        return $entry . ($indent . "],\n");
    }

    /**
     * Extracts string values from enum arrays.
     *
     * @param array<EntityType|OperationType> $enums Array of enum instances
     * @param string $enumClass The enum class for type hinting
     * @return array<string> Array of string values
     */
    private function extractEnumValues(array $enums, string $enumClass): array
    {
        return array_map(
            fn($enum): string => $enum->value,
            $enums
        );
    }

    /**
     * Formats array values for cache output.
     *
     * @param array<string> $values Values to format
     * @return string Formatted string for array declaration
     */
    private function formatArrayValues(array $values): string
    {
        return implode(', ', array_map(
            fn(string $value): string => sprintf("'%s'", $value),
            $values
        ));
    }
}
